WebApp/Controllers/ToyController.cs
using Fr.EQL.AI110.ChristmasFactory.Business;
using Fr.EQL.AI110.ChristmasFactory.Entities;
using Fr.EQL.AI110.ChristmasFactory.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.ChristmasFactory.Web.Controllers
{
    public class ToyController : Controller
    {
        [HttpPost]
        public IActionResult ExempleCategories(ToyCategoriesViewModel model)
        {
            return View(model); 
        }

        [HttpGet]
        public IActionResult ExempleCategories()
        {
            ToyBusiness bu = new ToyBusiness();
            ToyCategoriesViewModel model = new ToyCategoriesViewModel();
            model.Categories = bu.GetCategories(null); 
            return View(model);  
        }

        private IActionResult EditerToy(Toy toy)
        {
            ElfBusiness elfBu = new ElfBusiness();
            List<Elf> elves = elfBu.GetElves();
            ViewBag.ListeResponsables = elves;
            return View("Edit", toy);
        }

        [HttpGet]
        [Route("Nouveau-Jouet")]
        public IActionResult Create()
        {
            ViewData["reponse"] = 42;
            ViewBag.Formateur = "Benoit";

            return EditerToy(null);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            // /toy/update/42
            ToyBusiness tbu = new ToyBusiness();
            Toy toy = tbu.GetToyById(id);

            return EditerToy(toy);
        }

        public IActionResult Delete(int id)
        {
            ToyBusiness bu = new ToyBusiness();
            bu.DeleteToy(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Update(Toy toy)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ToyBusiness tbu = new ToyBusiness();
                    tbu.SaveToy(toy);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
            }
            else
            {
                return EditerToy(toy);
            }
        }

        [HttpPost]
        [Route("Nouveau-Jouet")]
        public IActionResult Create(Toy toy)
        {
            ToyBusiness bu = new ToyBusiness();
            bu.SaveToy(toy);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Index(ToySearchViewModel model)
        {
            ToyBusiness toyBU = new ToyBusiness();
            model.Toys = toyBU.SearchToys(model.IdResponsable, model.ToyName, model.MinPrice, model.MaxPrice);

            ElfBusiness elfBU = new ElfBusiness();
            model.Elves = elfBU.GetElves();

            return View(model);
        }

        [HttpGet]
        public IActionResult Index()
        {
            // récupérer le modele
            ToySearchViewModel model = new ToySearchViewModel();
            
            ToyBusiness toyBU = new ToyBusiness();
            model.Toys = toyBU.SearchToys(0, "", 0, 0);

            ElfBusiness elfBU = new ElfBusiness();
            model.Elves = elfBU.GetElves();

            // charger la vue :
            return View(model);
        }
    }
}

WebApp/Views/Toy/Edit.cshtml
@using Fr.EQL.AI110.ChristmasFactory.Entities
@model Toy

@{
    //List<Elf> elves = (List<Elf>)ViewData["listeResponsables"];
    List<Elf> elves = ViewBag.ListeResponsables;
}

<h1>Edition d'un jouet</h1>

<form method="post">

    <label asp-for="Name">Nom :</label> 
    <input asp-for="Name"/>
    @Html.ValidationMessageFor(m => m.Name)
    <br/>
    <label asp-for="Description">Description :</label> 
    <textarea asp-for="Description"></textarea>
    <br/>
    <label asp-for="Price">Prix :</label> 
    <input asp-for="Price"/>
    @Html.ValidationMessageFor(m => m.Price)
    <br/>
    <label asp-for="IdResponsable">Responsable :</label>   
    @* Affichage de la liste d'elfes à partir du ViewData *@
    <select asp-for="IdResponsable">
        @foreach (Elf elf in elves)
        {
            <option value="@elf.Id">@elf.Name</option>
        }
    </select>
    <br/>
    <input type="submit" value="Enregistrer"/>
    @if (Model != null && Model.Id > 0)
    {
    <a asp-controller="Toy"
                    asp-action="Delete"
                    asp-route-id="@Model.Id">Supprimer</a>
    }
</form>

WebApp/Views/Toy/ExempleCategories.cshtml
@using Fr.EQL.AI110.ChristmasFactory.Entities
@using Fr.EQL.AI110.ChristmasFactory.Web.Models
@model ToyCategoriesViewModel

<form method="post">

<ul>
    @foreach (ToyCategory cat in Model.Categories)
    {
        <li>
            <input type="checkbox" name="SelectedCategories" value="@cat.Id"/>
            @cat.Name
            @if (cat.Children.Count > 0)
            {
                <ul>
                    @foreach (ToyCategory cat2 in cat.Children)
                    {
                        <li>
                            <input type="checkbox" name="SelectedSubCategories" value="@cat2.Id"/>
                            @cat2.Name
                            @if (cat2.Children.Count > 0)
                            {
                                <ul>
                                    @foreach (ToyCategory cat3 in cat2.Children)
                                    {
                                        <li>
                                            <input type="checkbox" name="SelectedSubSubCategories" value="@cat3.Id"/>
                                            @cat3.Name
                                        </li>
                                    }
                                </ul>
                            }
                        </li>
                    }
                </ul>
            }
        </li>   
    }
</ul>

<input type="submit" value="OK"/>

</form>

WebApp/Views/Toy/Index.cshtml
@using Fr.EQL.AI110.ChristmasFactory.Entities
@using Fr.EQL.AI110.ChristmasFactory.Web.Models
@model ToySearchViewModel

<h1>Catalogue du père Noël</h1>

@Html.RouteLink("Nouveau", new {controller="toy", action="create"})

<div>
    <form method="post">
        Responsable : 
        <select asp-for="IdResponsable">
            <option value="0">Tous...</option>
            @foreach (Elf elf in Model.Elves)
            {
                <option value="@elf.Id">@elf.Name</option>
            }
        </select>

        Nom : <input asp-for="ToyName"/>

        Prix entre <input asp-for="MinPrice"/>
        et <input asp-for="MaxPrice"/>

        <input type="submit" value="Filtrer"/>
    </form>
</div>

<section class="catalogue">

    @foreach (ToyDetails toy in Model.Toys)
    {
    <article>
        <header><a asp-controller="toy"
                    asp-action="update"
                    asp-route-id="@toy.Id">@toy.Name</a></header>
        <span class="prix">@toy.Price €</span>
        <span>responsable : @toy.RespName</span>
    </article>
    }
</section>